ci: do not fail when no secrets available

diff --git a/.builds/ci.yml b/.builds/ci.yml
--- a/.builds/ci.yml
+++ b/.builds/ci.yml
@@ -54,7 +54,7 @@ tasks:
         export ARGS="--cache-from $NAME --platform linux/arm64,linux/amd64 --tag $NAME --target slidge-$LEGACY --build-arg SLIDGE_PLUGIN=$LEGACY ."
         docker buildx build $ARGS
         if [ "$(git rev-parse master)" = "$(git rev-parse HEAD)" ]; then
-          docker buildx build --push $ARGS
+          docker buildx build --push $ARGS || echo "We can't push to docker.io, continuing anyway"
         fi
       done
   - release: |
